config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :passwords do
    resources :shares, only: [:new, :create, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "passwords#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/password.rb
class Password < ApplicationRecord
  has_many :user_passwords, dependent: :destroy
  has_many :users, through: :user_passwords

  encrypts :username, deterministic: true
  encrypts :password

  validates :url, :username, :password, presence: true

  def shareable_users
    User.excluding(users)
  end

  def editable_by?(user)
    user_passwords.find_by(user: user).editable?
  end

  def shareable_by?(user)
    user_passwords.find_by(user: user).shareable?
  end

  def deletable_by?(user)
    user_passwords.find_by(user: user).deletable?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :user_passwords, dependent: :destroy
  has_many :passwords, through: :user_passwords
end

app/models/user_password.rb
class UserPassword < ApplicationRecord
  ROLES = %w[viewer editor owner]

  belongs_to :user
  belongs_to :password

  validates :role, presence: true, inclusion:  {in: ROLES}

  attribute :role, default: :viewer
  def owner?
    role == 'owner'
  end

  def viewer?
    role == 'viewer'
  end

  def editor?
    role == 'editor'
  end

  def editable?
    owner? || editor?
  end

  def shareable?
    owner?
  end

  def deletable?
    owner?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :user_password

  def user_password
    @user_password ||= current_user.user_passwords.find_by(password: @password)
  end

end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_password, only: [:show, :edit, :update, :destroy]
  before_action :require_editor_permissions, only: [:edit, :update, :destroy]
  before_action :require_owner_permissions, only: [:destroy]

  def index
    @passwords = current_user.passwords
  end

  def new
    @password = Password.new
  end

  def create
    @password = Password.new(password_params)

    @password.user_passwords.new(user: current_user, role: :owner)

    if @password.save
      redirect_to @password
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit

  end

  def update
    if @password.update(password_params)
      redirect_to @password
    else
      redirect_to :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @password.destroy
    redirect_to root_path
  end

  private
  def password_params
    params.require(:password).permit(:url, :username, :password)
  end

  def set_password
    @password = current_user.passwords.find(params[:id])
  end

  def require_owner_permissions
    redirect_to @password unless @user_password.deletable?
  end
  def require_editor_permissions
    redirect_to @password unless @user_password.editable?
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_password
  before_action :require_shareable_permission

  def new
    @user_password = UserPassword.new
  end

  def create
    @user_password = @password.user_passwords.new(user_password_params)

    if @user_password.save
      redirect_to @password
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @password.user_passwords.where(user_id: params[:id]).destroy_all
    redirect_to @password
  end

  private
  def set_password
    @password = current_user.passwords.find(params[:password_id])
  end

  def user_password_params
    params.require(:user_password).permit(:user_id, :role)
  end

  def require_shareable_permission
    redirect_to @password unless user_password.shareable?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="flex justify-between">
  <div class="flex gap-2 items-center">
    <%= link_to "Password Manager", root_path, class: 'text-xl font-bold no-underline' %>
  </div>

  <ul class="list-none flex items-center gap-2">
    <% if user_signed_in? %>
      <li><%= link_to 'Profile', edit_user_registration_path %></li>
      <li><%= button_to 'Logout', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Login', new_user_session_path %></li>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PasswordManager</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <main class="container mx-auto">
    <div class="prose max-w-none px-5">
      <%= render "layouts/navbar" %>
      <%= render "shared/flash" %>

      <%= yield %>
    </div>
  </main>
</body>
</html>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="p-4 rounded bg-green-100 text-green-800 mb-3"><%= notice %></div>
<% end %>

<% if alert %>
  <div class="p-4 rounded bg-red-100 text-red-800 mb-3"><%= alert %></div>
<% end %>

app/views/shares/new.html.erb
<h1>Share Password</h1>

<%= form_with model: [@password, @user_password], url: password_shares_path(@password) do |form| %>
  <div>
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, @password.shareable_users, :id, :email %>
  </div>

  <div>
    <%= form.label :role %>
    <%= form.select :role, UserPassword::ROLES.map { |role| [role.titleize, role] } %>
  </div>

  <div>
    <%= form.submit "Share Password" %>
  </div>
<% end %>